// import './spec/Options.spec'
//import './spec/html.spec'
//import './spec/source.spec'
import './spec/domain/effects.spec'
// import './spec/Domain.spec'
//import './spec/reconcile.spec'
//import './spec/html/inheritance.spec'
//import './spec/html/properties.spec'
//import './spec/html/calculated-items.spec'
// import './spec/source/calculated-props.spec'
//import './spec/sandbox/scope.spec'