// import './spec/Options.spec'
import './spec/html.spec'
import './spec/source.spec'
// import './spec/Domain.spec'
import './spec/reconcile.spec'
import './spec/html/calculated-items.spec'
import './spec/source/calculated-props.spec'
